### ISSUE TITLE
Can not open Applied Energistics 2 Crafting-Window

### ISSUE THREAD

**Issue by Motzkiste** [LavaPowered/Lava#8] opened 2019-07-14 19:33 UTC
Hi,

First of all thank you for your Very good Serversoftware. ^^

My Server crashed instand after a join-timeout (My Client "crashed"... ALT+F4 the wrong window)
But since it's the second or third time the server crashed due to an join-timeout i thougth I should report this.

[Crashlog from Console](https://pastebin.com/7rWW3aTj)
[Crashreport](https://pastebin.com/4BpwLczL)

I hope this is the right place to report this.

I used the build-version f5f730f, because the latest pre-compiled jar did not work.

EDIT: Fixed this though deleting my Playerdata.
---

Now another Problem: Everytime I Join and an the Server loads an Ender Zoo Entity it crashes with Error `ticking world`.

[Crashreport](https://pastebin.com/MmqQbGKg)

**Comment by GMatrixGames** [comment] 2019-07-14 23:36
It seems EnderZoo can't load it's own class, I'll leave this open though since you may have more questions.

- GMatrixGames

**Comment by Motzkiste** [comment] 2019-07-15 11:00
The Error does not happen with normal Forge + Sponge (And even without Sponge it does work)

So are you sure that this Error has nothing to do with Lava?

**Comment by Motzkiste** [comment] 2019-08-01 14:37
Hey,

I tried again with newest Lava Version. 

Now there is no more Ticking World Error ^^
And yes with the same Mod-Versions.

Now I have another Error when I try to click on an craftable item in Applied Energistics 2:
[Error from Console](https://pastebin.com/XhkCFQBQ)

Does not open Crafting Window.

**Comment by GMatrixGames** [comment] 2019-08-07 02:40
I'm assuming the issue was caused by an implementation of non-bukkit inventory loading which should be fixed now. But the new builds cannot be run due to a world loading/unloading issue.

Sorry
- GMatrixGames

**Closed** 2019-12-03 01:11 UTC
