### ISSUE TITLE
MagicSpells issue

### ISSUE THREAD

**Issue by gundom0802** [LavaPowered/Lava#5] opened 2019-07-02 01:13 UTC
Hi there! The lava api is amazing. Good job to you GMatrix. Only problem is that direct targeted spells do not work on MagicSpells. Here are the code towards some of the spells that do not work:https://github.com/TheComputerGeek2/MagicSpells/blob/master/src/com/nisovin/magicspells/spells/targeted/PotionEffectSpell.java

https://github.com/TheComputerGeek2/MagicSpells/blob/master/src/com/nisovin/magicspells/spells/targeted/StunSpell.java

Hopefully, this can be fixed soon :)

**Comment by GMatrixGames** [comment] 2019-07-02 13:49
I think this is caused by the PotionEffectType injector. Will follow up with more info.

**Comment by GMatrixGames** [comment] 2019-08-07 02:44
Issue might be fixed in latest versions, but they cannot be run as there's a loading issue with worlds. I'll post an update in the discord once we have a fix for that issue.

**Closed** 2019-12-03 01:11 UTC
